version: "3.8"
services:
  softether_vpn:
    image: siomiz/softethervpn
    cap_add:
      - NET_ADMIN
    ports:
      - 443:443
      - 500:500/udp
      - 4500:4500/udp
      - 1701:1701/tcp
      - 5555:5555/tcp
    environment:
      - SPW=${MNG_PW}
      - HPW=${MNG_PW}
      - PSK=${PSK}
      - USERS=${USER}:${PASSWD}
    restart:
      unless-stopped
